################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
S_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
S_DEPS := 
CXX_DEPS := 
C_UPPER_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Projects/XilinxFpgaProg \
Projects/XPLAINBridge \
Projects/XPLAINBridge/Lib \
Projects/Webserver \
Projects/Webserver/Lib/uip \
Projects/Webserver/Lib \
Projects/Webserver/Lib/FATFs \
Projects/USBtoSerial \
Projects/TempDataLogger \
Projects/TempDataLogger/Lib \
Projects/TempDataLogger/Lib/FATFs \
Projects/SerialToLCD \
Projects/SerialToLCD/Lib \
Projects/RelayBoard \
Projects/MissileLauncher \
Projects/MediaController \
Projects/Magstripe \
Projects/Magstripe/Lib \
Projects/MIDIToneGenerator \
Projects/LEDNotifier \
Projects/HIDReportViewer \
Projects/Benito \
Projects/AVRISP-MKII/Lib/XPROG \
Projects/AVRISP-MKII/Lib \
Projects/AVRISP-MKII/Lib/ISP \
Projects/AVRISP-MKII \
LUFA/Platform/UC3 \
LUFA/Drivers/USB/Core/XMEGA \
LUFA/Drivers/USB/Core/XMEGA/Template \
LUFA/Drivers/USB/Core \
LUFA/Drivers/USB/Core/UC3 \
LUFA/Drivers/USB/Core/UC3/Template \
LUFA/Drivers/USB/Core/AVR8 \
LUFA/Drivers/USB/Core/AVR8/Template \
LUFA/Drivers/USB/Class/Host \
LUFA/Drivers/USB/Class/Device \
LUFA/Drivers/USB/Class/Common \
LUFA/Drivers/Peripheral/XMEGA \
LUFA/Drivers/Peripheral/AVR8 \
LUFA/Drivers/Board \
LUFA/Build/HID_EEPROM_Loader \
Demos/Host/LowLevel/VirtualSerialHost \
Demos/Host/LowLevel/StillImageHost \
Demos/Host/LowLevel/StillImageHost/Lib \
Demos/Host/LowLevel/RNDISEthernetHost \
Demos/Host/LowLevel/RNDISEthernetHost/Lib \
Demos/Host/LowLevel/PrinterHost \
Demos/Host/LowLevel/PrinterHost/Lib \
Demos/Host/LowLevel/MouseHostWithParser \
Demos/Host/LowLevel/MouseHost \
Demos/Host/LowLevel/MassStorageHost \
Demos/Host/LowLevel/MassStorageHost/Lib \
Demos/Host/LowLevel/MIDIHost \
Demos/Host/LowLevel/KeyboardHostWithParser \
Demos/Host/LowLevel/KeyboardHost \
Demos/Host/LowLevel/JoystickHostWithParser \
Demos/Host/LowLevel/GenericHIDHost \
Demos/Host/LowLevel/AudioOutputHost \
Demos/Host/LowLevel/AudioInputHost \
Demos/Host/LowLevel/AndroidAccessoryHost/Lib \
Demos/Host/LowLevel/AndroidAccessoryHost \
Demos/Host/ClassDriver/VirtualSerialHost \
Demos/Host/ClassDriver/StillImageHost \
Demos/Host/ClassDriver/RNDISEthernetHost \
Demos/Host/ClassDriver/PrinterHost \
Demos/Host/ClassDriver/MouseHostWithParser \
Demos/Host/ClassDriver/MouseHost \
Demos/Host/ClassDriver/MassStorageHost \
Demos/Host/ClassDriver/MIDIHost \
Demos/Host/ClassDriver/KeyboardHostWithParser \
Demos/Host/ClassDriver/KeyboardHost \
Demos/Host/ClassDriver/JoystickHostWithParser \
Demos/Host/ClassDriver/AudioOutputHost \
Demos/Host/ClassDriver/AudioInputHost \
Demos/Host/ClassDriver/AndroidAccessoryHost \
Demos/DualRole/ClassDriver/MouseHostDevice \
Demos/Device/LowLevel/VirtualSerial \
Demos/Device/LowLevel/RNDISEthernet \
Demos/Device/LowLevel/RNDISEthernet/Lib \
Demos/Device/LowLevel/Mouse \
Demos/Device/LowLevel/MassStorage \
Demos/Device/LowLevel/MassStorage/Lib \
Demos/Device/LowLevel/MIDI \
Demos/Device/LowLevel/KeyboardMouse \
Demos/Device/LowLevel/Keyboard \
Demos/Device/LowLevel/Joystick \
Demos/Device/LowLevel/GenericHID \
Demos/Device/LowLevel/DualVirtualSerial \
Demos/Device/LowLevel/AudioOutput \
Demos/Device/LowLevel/AudioInput \
Demos/Device/Incomplete/TestAndMeasurement \
Demos/Device/Incomplete/Sideshow \
Demos/Device/Incomplete/Sideshow/Lib \
Demos/Device/ClassDriver/VirtualSerialMouse \
Demos/Device/ClassDriver/VirtualSerialMassStorage \
Demos/Device/ClassDriver/VirtualSerialMassStorage/Lib \
Demos/Device/ClassDriver/VirtualSerial \
Demos/Device/ClassDriver/RNDISEthernet \
Demos/Device/ClassDriver/RNDISEthernet/Lib \
Demos/Device/ClassDriver/Mouse \
Demos/Device/ClassDriver/MassStorageKeyboard \
Demos/Device/ClassDriver/MassStorageKeyboard/Lib \
Demos/Device/ClassDriver/MassStorage \
Demos/Device/ClassDriver/MassStorage/Lib \
Demos/Device/ClassDriver/MIDI \
Demos/Device/ClassDriver/KeyboardMouseMultiReport \
Demos/Device/ClassDriver/KeyboardMouse \
Demos/Device/ClassDriver/Keyboard \
Demos/Device/ClassDriver/Joystick \
Demos/Device/ClassDriver/GenericHID \
Demos/Device/ClassDriver/DualVirtualSerial \
Demos/Device/ClassDriver/AudioOutput \
Demos/Device/ClassDriver/AudioInput \
BuildTests/SingleUSBModeTest \
BuildTests/ModuleTest \
BuildTests/BoardDriverTest \
Bootloaders/HID/HostLoaderApp \
Bootloaders/HID \
Bootloaders/DFU \
Bootloaders/CDC \

